config/routes.rb
Rails.application.routes.draw do
  resources :cities
  end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: %i[ show edit update destroy ]

  # GET /cities or /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1 or /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities or /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to city_url(@city), notice: "City was successfully created." }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1 or /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to city_url(@city), notice: "City was successfully updated." }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1 or /cities/1.json
  def destroy
    @city.destroy

    respond_to do |format|
      format.html { redirect_to cities_url, notice: "City was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def city_params
      params.require(:city).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def data_br(data_us)
        data_us.strftime("%d/%m/%Y")
    end
    
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_city.html.erb
<div id="<%= dom_id city %>">
  <p>
    <strong>Nome:</strong>
    <%= city.name %>
  </p>

</div>

app/views/cities/_form.html.erb
<%= form_with(model: city) do |form| %>
  <% if city.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(city.errors.count, "error") %> Cidade não foi cadastrada!:</h2>

      <ul>
        <% city.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editdando cidade</h1>

<%= render "form", city: @city %>

<br>

<div>
  <%= link_to "Detalhes da Cidade", @city %> |
  <%= link_to "Voltar para Cidades", cities_path %>
</div>

app/views/cities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cidades</h1>

<div id="cities">
  <% @cities.each do |city| %>
    <%= render city %>
    <p>
      <%= link_to "Detalhes da cidade", city %>
    </p>
  <% end %>
</div>

<%= link_to "Cadastrar nova cidade", new_city_path %>

app/views/cities/new.html.erb
<h1>Cadastrar Cidade</h1>

<%= render "form", city: @city %>

<br>

<div>
  <%= link_to "Voltar para cidades", cities_path %>
</div>

app/views/cities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @city %>

<div>
  <%= link_to "Editar essa cidade", edit_city_path(@city) %> |
  <%= link_to "Voltar para Cidades", cities_path %>

  <%= button_to "Apagar registro de  cidade", @city, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Golias</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <%= render "partials/cabecalho" %> 
     <div>
             <%= yield %>
     <div>
         <%= render "partials/rodape" %> 
    <div>
  </body>
</html>

app/views/partials/_cabecalho.html.erb
<div class="container-fluid">
  <div class="cabecalho"  >
      <div class="row">
          <div class="col" id="logo" >
            <%= image_tag("/logo.png", :size=> "70x70") %>
            </div>
            <div class="col text-center" id="golias">
               <h4>Sistema de Gerenciamento Pericial</h4>
            </div>
            <div class="col text-center" id="golias">
               <p><strong>Data</strong></p>
               <%= data_br(Date.today) %>
            </div>
      </div>
  </div>
</div>

<style>
  div.cabecalho{
    padding: 0;
    margin:0;
    box-sizing:border-box;
    height:70px;
    width:100%;
    color:white;
    background-color:black
  }
 
<style>
 

app/views/partials/_rodape.html.erb
<div class="container-fluid">
  <div class="rodape"  >
      <div class="row">
          <div class="col" id="logo" >
            <%= image_tag("/logo.png", :size=> "70x70") %>
            </div>
            <div class="col text-center" id="golias">
               <h6>Desenvolvido por Sttefani Ribeiro</h6>
            </div>
            <div class="col text-center" id="golias">
               <p><strong>Contato</strong></p>
               <p> 95 991143501 </p>
            </div>
      </div>
  </div>
</div>

<style>
  div.rodape{
    padding: 0;
    margin:0;
    box-sizing:border-box;
    height:70px;
    width:100%;
    color:white;
    background-color:black;
    position:absolute;
  }
 
<style>
  
  